[default]
api_key="zwt_hkkdiZC4wcHVUcFzbPMI9C60WXspKnUWpN9Wkw"

[Corpus2]
api_key="zwt_hkkdidRcx49sOx-7zzL9uDtQXhAJQk1SyX_TTw"

[Corpus3]
api_key="zwt_hkkdiZL12kbdwQ0fq9Vxck3Og4wtJqbW80A5yQ"
NOTION_API_KEY="secret_hxChZYERzQVXutMtoQT1kGVLhvvoHn3vpkTMQ4dRiZt"

[Corpus4]
api_key="zwt_hkkdie2-9vfd3F104Xm7ph-bC9rw4zpNsehoIw"

[Corpus6]
api_key="zwt_hkkdidrEx37Nyf4osF8vpyWpVfgAJT52zzBdVA"