vectara:
  corpus_id: 4
  customer_id: 2252938633
  reindex: false

crawling:
  crawler_type: docs

docs_crawler:
  base_urls: ['https://www.jscamp.app']
  pos_regex: ['https://www.jscamp.app/docs.*']
  docs_repo: 'https://github.com/gHashTag/jscamp'
  docs_homepage: 'https://www.jscamp.app/docs'
  docs_system: 'docusaurus'
  neg_regex: []
  extensions_to_ignore: ['md', 'rst', 'ipynb', 'txt']
